// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-CJBDlPXW2Am9bs4B_QgNGFCUkTTpqYw',
    appId: '1:1022652091327:web:6353851cf522aa94efaf0a',
    messagingSenderId: '1022652091327',
    projectId: 'login-aaed7',
    authDomain: 'login-aaed7.firebaseapp.com',
    storageBucket: 'login-aaed7.firebasestorage.app',
    measurementId: 'G-0M4T1NTJTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABSNlHMI-UG7-LvfS8k-eo3ys3ExzzR04',
    appId: '1:1022652091327:android:56b70e0d203ccdb7efaf0a',
    messagingSenderId: '1022652091327',
    projectId: 'login-aaed7',
    storageBucket: 'login-aaed7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPZGXm7msYGt9Z1mSZNJzkmFHsJBW3YNs',
    appId: '1:1022652091327:ios:efe603147747edfdefaf0a',
    messagingSenderId: '1022652091327',
    projectId: 'login-aaed7',
    storageBucket: 'login-aaed7.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPZGXm7msYGt9Z1mSZNJzkmFHsJBW3YNs',
    appId: '1:1022652091327:ios:efe603147747edfdefaf0a',
    messagingSenderId: '1022652091327',
    projectId: 'login-aaed7',
    storageBucket: 'login-aaed7.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-CJBDlPXW2Am9bs4B_QgNGFCUkTTpqYw',
    appId: '1:1022652091327:web:fc17889e8cc83c2defaf0a',
    messagingSenderId: '1022652091327',
    projectId: 'login-aaed7',
    authDomain: 'login-aaed7.firebaseapp.com',
    storageBucket: 'login-aaed7.firebasestorage.app',
    measurementId: 'G-TVKY5B091P',
  );
}
